name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPUnit tests
      run: composer test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Check if Site Exists
        id: check_site
        run: |
          if netlify sites:list | grep -q "CS event management system"; then
            echo "Site exists"
          else
            echo "Site does not exist"
          fi

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir src public --name "CS event management system"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
