name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install

    - name: Add vendor/bin to PATH
      run: echo "export PATH=$(pwd)/vendor/bin:\$PATH" >> $GITHUB_ENV

    - name: Debug - List vendor/bin contents
      run: ls -l vendor/bin

    - name: Debug - Print PATH
      run: echo $PATH

    - name: Refresh environment
      run: source $GITHUB_ENV

    - name: Run PHPUnit tests
      run: phpunit
